# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwaQr < Formula
  desc "QR-Code generator for checking into events using the Corona Warn App"
  homepage "https://github.com/lukasmalkmus/cwa-qr"
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/lukasmalkmus/cwa-qr/releases/download/v0.2.0/cwa-qr_0.2.0_darwin_amd64.tar.gz"
    sha256 "0d00ace72542ddead6db49523edab3e6f425461bb975c748ceb162d3f1e88644"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/lukasmalkmus/cwa-qr/releases/download/v0.2.0/cwa-qr_0.2.0_darwin_arm64.tar.gz"
    sha256 "364af1853ebb3080cdeb73278ca356dcc522c64a33dab7c9d833935086b54dba"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/lukasmalkmus/cwa-qr/releases/download/v0.2.0/cwa-qr_0.2.0_linux_amd64.tar.gz"
    sha256 "5577ef84d23953f8923f70db25ef42bbb9b4bd4250d900eb4b50ebad707aec08"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/lukasmalkmus/cwa-qr/releases/download/v0.2.0/cwa-qr_0.2.0_linux_armv6.tar.gz"
    sha256 "bfa1a3c3952726639e0b60e922feefc0566b81ae341051d35e0bbca7da06724f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/lukasmalkmus/cwa-qr/releases/download/v0.2.0/cwa-qr_0.2.0_linux_arm64.tar.gz"
    sha256 "a881172a9e97789a8a3ac2819f33165a6fa243ca4d0047201944225b270869d7"
  end

  def install
    bin.install "cwa-qr"
  end

  test do
    assert_match "Corona Warn App QR-Code Generator version #{version}", shell_output("#{bin}/cwa-qr -version")
  end
end
