# This file was generated by GoReleaser. DO NOT EDIT.
class Expensso < Formula
  desc "Seamless budgeting from the comfort of your command-line"
  homepage "https://lukasmalkmus.github.io/expensso"
  version "0.1.0"
  license "BSD-3-Clause"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lukasmalkmus/expensso/releases/download/v0.1.0/exp_0.1.0_darwin_amd64.tar.gz"
    sha256 "605b4eac3a57f931357a03bd52221cadbd1f12037c676d570d9e84078fc00c19"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/lukasmalkmus/expensso/releases/download/v0.1.0/exp_0.1.0_linux_amd64.tar.gz"
    sha256 "6f96fb55064d5884d540eda221acaaaa5d9eb7cd190556fe78abd54d1e028c76"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/lukasmalkmus/expensso/releases/download/v0.1.0/exp_0.1.0_linux_arm64.tar.gz"
    sha256 "43c42afb13c889dadf99b179bf3770b64efe89d81258a352735fb385f306999f"
  end

  def install
    bin.install "exp"
    man1.install Dir["dist/man/exp*.1"]
    (bash_completion/"exp").write `#{bin}/exp completion bash`
    (fish_completion/"exp.fish").write `#{bin}/exp completion fish`
    (zsh_completion/"_exp").write `#{bin}/exp completion zsh`
  end

  test do
    assert_match "Expensso CLI version #{version}", shell_output("#{bin}/exp -v")
  end
end
