# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Horcrux < Formula
  desc "Security question based secret sharing utility"
  homepage "https://github.com/lukasmalkmus/horcrux"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lukasmalkmus/horcrux/releases/download/v0.1.0/horcrux_0.1.0_darwin_amd64.tar.gz"
      sha256 "23a2e5b759f65d8debd0a0e8470437de86dd37b7a8973e05d3270dd98d4f0632"
    end
    if Hardware::CPU.arm?
      url "https://github.com/lukasmalkmus/horcrux/releases/download/v0.1.0/horcrux_0.1.0_darwin_arm64.tar.gz"
      sha256 "891dfcc13c9d1f898d3380cdd9929b49deb95b34a4b85d02a8c67d506279826c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lukasmalkmus/horcrux/releases/download/v0.1.0/horcrux_0.1.0_linux_amd64.tar.gz"
      sha256 "869957723c3646c373c71058fdfd3e7665ed7445e9918c9c01a439ae121d693f"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lukasmalkmus/horcrux/releases/download/v0.1.0/horcrux_0.1.0_linux_armv6.tar.gz"
      sha256 "026fbce8d7741a7619e4fbb13bd08dc6ba0d264c0448ff594bb4503cf3f8ae10"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukasmalkmus/horcrux/releases/download/v0.1.0/horcrux_0.1.0_linux_arm64.tar.gz"
      sha256 "7cf985081b95c33aa6298c4400188ea1eef89694c4241a26970f3e39ff349873"
    end
  end

  def install
    bin.install "horcrux"
  end

  test do
    assert_match "horcrux version #{version}", shell_output("#{bin}/horcrux -v")
  end
end
