# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Horcrux < Formula
  desc "Security question based secret sharing utility"
  homepage "https://github.com/lukasmalkmus/horcrux"
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lukasmalkmus/horcrux/releases/download/v0.2.0/horcrux_0.2.0_darwin_amd64.tar.gz"
      sha256 "297122560b1c8f0145659489269f3fb1710701f1175bf6e1d3b6ed66e11a520f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/lukasmalkmus/horcrux/releases/download/v0.2.0/horcrux_0.2.0_darwin_arm64.tar.gz"
      sha256 "79fc3a95b5234a48c4c0c0913517f6a3f452edcaad15f1b0a6d66adbf2966d15"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lukasmalkmus/horcrux/releases/download/v0.2.0/horcrux_0.2.0_linux_amd64.tar.gz"
      sha256 "5d8218e5a4256b7c1282053ceb49316ad1a183fe5789955f6743cf54f8bc9d3b"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lukasmalkmus/horcrux/releases/download/v0.2.0/horcrux_0.2.0_linux_armv6.tar.gz"
      sha256 "a265029fdf8763d5557e217246fb072d83e480045582a32b68669b21cc82dc86"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukasmalkmus/horcrux/releases/download/v0.2.0/horcrux_0.2.0_linux_arm64.tar.gz"
      sha256 "99fe9304208b8ecf64945a351990ed70c1e21e7b0b4aaf00ad2ad5ba535bd616"
    end
  end

  def install
    bin.install "horcrux"
  end

  test do
    assert_match "horcrux version #{version}", shell_output("#{bin}/horcrux -v")
  end
end
