name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        formula:
          - cwa-qr
          - horcrux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - name: Install Formula ${{ matrix.formula }}
        run: |
          brew audit ${{ matrix.formula }}
          brew install -v ${{ matrix.formula }}
          # brew test ${{ matrix.formula }}
